#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server

filePath="$1"
serverIp="$2"
scpUsername="$3"
sshPrivateKey"$4"

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else
	scp -0 "StrictHostKeyChecking=no" -i "$sshPrivateKey" "$filePath" "$scpUserName@$serverIp":~/;
fi
