#!/usr/bin/env bash
# Script that install Nginx on my web server

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
