#!/usr/bin/env bash
# Script that configures Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Configure Nginx
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Create a simple index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure redirection for /redirect_me with a 301 Moved Permanently
my_string="Ceci n'est pas une page"
redirect_config="server_name _;\n\tlocation /xyz {\n\t\treturn 404 $my_string;\n\t}"
sudo sed -i "/server_name _;/c\\$redirect_config" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart

echo "Nginx configuration completed. Your server is now redirecting /redirect_me with a 301 Moved Permanently to redirection site"
