#!/usr/bin/env bash
# Script that automates nginx installation to listen to port 80.
# i started by trying with my local machine. accesssed the file /etc/nginx/nginx.conf and added the block
# server {
#   listen 80;
#    server_name _;
#}
# Then for the main task, i created a copy of the sites-available file to sites-enabled, using symbolic links(-s)
# the -f flag is to force the creation of the symlink even if it already exists, overwriting it if necessary.
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
